//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_laba4_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceShips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpaceShips()
        {
            this.PilotsOfShip = new HashSet<PilotsOfShip>();
        }
    
        public int ID_SpaceShip { get; set; }
        public string NameShip { get; set; }
        public int AmountFlights { get; set; }
        public int TypeShip_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PilotsOfShip> PilotsOfShip { private get; set; }
        public virtual ShipsTypes ShipsTypes { private get; set; }
    }
}
